#!/bin/bash
if echo "X$1" | grep -q '^X-[a-zA-Z0-9]'; then 
    CMSBSUB_QUEUE=$(echo "X$1" | sed 's/^X-//');
    CMSBSUB_DOIT=1;
    shift;
fi;
if test -f $1 ; then echo "ERROR, $1 must be the EOS path for stage out. "; exit 1; fi
if echo $1 | grep -v -q '^/eos/cms/store/' ; then echo "ERROR, $1 must be the EOS path for stage out. "; exit 1; fi
eos ls $1 > /dev/null 2>&1 || $eos mkdir -p $1 2> /dev/null 
if eos ls $1 > /dev/null 2>&1 ; then
    echo "Will stage out the output in $1";
else
    echo "Directory $1 does not exist, and cannot create it. Aborting."
    exit 1
fi
if [[ "$CMSBSUB_QUEUE" == "" ]]; then CMSBSUB_DOIT=0; fi;
if [[ "$CMSBSUB_DOIT" == "1" ]]; then
    if bqueues $CMSBSUB_QUEUE > /dev/null; then
        bsub -q $CMSBSUB_QUEUE $PWD/scripts/cmsRunBatchEOS $PWD $*;	
    fi;
else
    echo bsub -q 8nh cmsRunBatchEOS $PWD $*
fi;
